/var/www/viabix/logs/*.log /var/log/viabix_backup.log /var/log/viabix_healthcheck.log {
    daily
    rotate 14
    missingok
    notifempty
    compress
    delaycompress
    copytruncate
    su www-data www-data
}