-- Fase 12 - Padronizacao segura do banco Viabix
-- Execute preferencialmente via api/schema_maintenance.php para obter relatorio.
-- Este arquivo serve como referencia SQL para ambientes onde a migracao e aplicada manualmente.

CREATE TABLE IF NOT EXISTS tenants (
    id CHAR(36) NOT NULL PRIMARY KEY,
    nome VARCHAR(150) NOT NULL DEFAULT 'Empresa',
    slug VARCHAR(120) NULL,
    ativo TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS projetos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tenant_id CHAR(36) NULL,
    dados LONGTEXT NULL,
    dados_financeiros_reais LONGTEXT NULL,
    criado_por CHAR(36) NULL,
    atualizado_por CHAR(36) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_projetos_tenant (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS logs_atividade (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tenant_id CHAR(36) NULL,
    usuario_id CHAR(36) NULL,
    acao VARCHAR(100) NOT NULL,
    entidade VARCHAR(80) NULL,
    entidade_id VARCHAR(80) NULL,
    detalhes TEXT NULL,
    ip_address VARCHAR(64) NULL,
    user_agent TEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_logs_tenant_created (tenant_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS tenant_id CHAR(36) NULL;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS login VARCHAR(100) NULL;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS email VARCHAR(150) NULL;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS ativo TINYINT(1) NOT NULL DEFAULT 1;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE anvis ADD COLUMN IF NOT EXISTS tenant_id CHAR(36) NULL;
ALTER TABLE anvis ADD COLUMN IF NOT EXISTS numero VARCHAR(50) NULL;
ALTER TABLE anvis ADD COLUMN IF NOT EXISTS revisao VARCHAR(20) NULL;
ALTER TABLE anvis ADD COLUMN IF NOT EXISTS cliente VARCHAR(255) NULL;
ALTER TABLE anvis ADD COLUMN IF NOT EXISTS projeto VARCHAR(255) NULL;
ALTER TABLE anvis ADD COLUMN IF NOT EXISTS produto VARCHAR(255) NULL;
ALTER TABLE anvis ADD COLUMN IF NOT EXISTS volume_mensal INT NULL DEFAULT 0;
ALTER TABLE anvis ADD COLUMN IF NOT EXISTS data_anvi DATE NULL;
ALTER TABLE anvis ADD COLUMN IF NOT EXISTS status VARCHAR(40) NOT NULL DEFAULT 'em-andamento';
ALTER TABLE anvis ADD COLUMN IF NOT EXISTS dados LONGTEXT NULL;
ALTER TABLE anvis ADD COLUMN IF NOT EXISTS dados_financeiros LONGTEXT NULL;
ALTER TABLE anvis ADD COLUMN IF NOT EXISTS projeto_id INT NULL;
ALTER TABLE anvis ADD COLUMN IF NOT EXISTS versao INT NOT NULL DEFAULT 1;
ALTER TABLE anvis ADD COLUMN IF NOT EXISTS hash_conteudo VARCHAR(64) NULL;
ALTER TABLE anvis ADD COLUMN IF NOT EXISTS criado_por CHAR(36) NULL;
ALTER TABLE anvis ADD COLUMN IF NOT EXISTS atualizado_por CHAR(36) NULL;
ALTER TABLE anvis ADD COLUMN IF NOT EXISTS data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE anvis ADD COLUMN IF NOT EXISTS data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE projetos ADD COLUMN IF NOT EXISTS tenant_id CHAR(36) NULL;
ALTER TABLE projetos ADD COLUMN IF NOT EXISTS dados LONGTEXT NULL;
ALTER TABLE projetos ADD COLUMN IF NOT EXISTS dados_financeiros_reais LONGTEXT NULL;
ALTER TABLE projetos ADD COLUMN IF NOT EXISTS criado_por CHAR(36) NULL;
ALTER TABLE projetos ADD COLUMN IF NOT EXISTS atualizado_por CHAR(36) NULL;
ALTER TABLE projetos ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE projetos ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
